/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function n(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}}function q(a){var d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return d?d.call(a):{next:n(a)}}function r(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<a.length;++d){var c=a[d];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}
var u=r(this),v="function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,c){if(a==Array.prototype||a==Object.prototype)return a;a[d]=c.value;return a};function x(a,d){if(d)a:{var c=u;a=a.split(".");for(var b=0;b<a.length-1;b++){var h=a[b];if(!(h in c))break a;c=c[h]}a=a[a.length-1];b=c[a];d=d(b);d!=b&&null!=d&&v(c,a,{configurable:!0,writable:!0,value:d})}}
x("Symbol",function(a){function d(h){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new c("jscomp_symbol_"+(h||"")+"_"+b++,h)}function c(h,l){this.a=h;v(this,"description",{configurable:!0,writable:!0,value:l})}if(a)return a;c.prototype.toString=function(){return this.a};var b=0;return d});
x("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var d="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<d.length;c++){var b=u[d[c]];"function"===typeof b&&"function"!=typeof b.prototype[a]&&v(b.prototype,a,{configurable:!0,writable:!0,value:function(){return y(n(this))}})}return a});function y(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function z(a,d){return Object.prototype.hasOwnProperty.call(a,d)}
x("WeakMap",function(a){function d(e){this.a=(f+=Math.random()+1).toString();if(e){e=q(e);for(var g;!(g=e.next()).done;)g=g.value,this.set(g[0],g[1])}}function c(){}function b(e){var g=typeof e;return"object"===g&&null!==e||"function"===g}function h(e){if(!z(e,m)){var g=new c;v(e,m,{value:g})}}function l(e){var g=Object[e];g&&(Object[e]=function(k){if(k instanceof c)return k;Object.isExtensible(k)&&h(k);return g(k)})}if(function(){if(!a||!Object.seal)return!1;try{var e=Object.seal({}),g=Object.seal({}),
k=new a([[e,2],[g,3]]);if(2!=k.get(e)||3!=k.get(g))return!1;k.delete(e);k.set(g,4);return!k.has(e)&&4==k.get(g)}catch(p){return!1}}())return a;var m="$jscomp_hidden_"+Math.random();l("freeze");l("preventExtensions");l("seal");var f=0;d.prototype.set=function(e,g){if(!b(e))throw Error("Invalid WeakMap key");h(e);if(!z(e,m))throw Error("WeakMap key fail: "+e);e[m][this.a]=g;return this};d.prototype.get=function(e){return b(e)&&z(e,m)?e[m][this.a]:void 0};d.prototype.has=function(e){return b(e)&&z(e,
m)&&z(e[m],this.a)};d.prototype.delete=function(e){return b(e)&&z(e,m)&&z(e[m],this.a)?delete e[m][this.a]:!1};return d});
x("Map",function(a){function d(){var f={};return f.f=f.next=f.head=f}function c(f,e){var g=f.a;return y(function(){if(g){for(;g.head!=f.a;)g=g.f;for(;g.next!=g.head;)return g=g.next,{done:!1,value:e(g)};g=null}return{done:!0,value:void 0}})}function b(f,e){var g=e&&typeof e;"object"==g||"function"==g?l.has(e)?g=l.get(e):(g=""+ ++m,l.set(e,g)):g="p_"+e;var k=f.b[g];if(k&&z(f.b,g))for(f=0;f<k.length;f++){var p=k[f];if(e!==e&&p.key!==p.key||e===p.key)return{id:g,list:k,index:f,c:p}}return{id:g,list:k,
index:-1,c:void 0}}function h(f){this.b={};this.a=d();this.size=0;if(f){f=q(f);for(var e;!(e=f.next()).done;)e=e.value,this.set(e[0],e[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var f=Object.seal({x:4}),e=new a(q([[f,"s"]]));if("s"!=e.get(f)||1!=e.size||e.get({x:4})||e.set({x:4},"t")!=e||2!=e.size)return!1;var g=e.entries(),k=g.next();if(k.done||k.value[0]!=f||"s"!=k.value[1])return!1;k=g.next();return k.done||4!=k.value[0].x||
"t"!=k.value[1]||!g.next().done?!1:!0}catch(p){return!1}}())return a;var l=new WeakMap;h.prototype.set=function(f,e){f=0===f?0:f;var g=b(this,f);g.list||(g.list=this.b[g.id]=[]);g.c?g.c.value=e:(g.c={next:this.a,f:this.a.f,head:this.a,key:f,value:e},g.list.push(g.c),this.a.f.next=g.c,this.a.f=g.c,this.size++);return this};h.prototype.delete=function(f){f=b(this,f);return f.c&&f.list?(f.list.splice(f.index,1),f.list.length||delete this.b[f.id],f.c.f.next=f.c.next,f.c.next.f=f.c.f,f.c.head=null,this.size--,
!0):!1};h.prototype.clear=function(){this.b={};this.a=this.a.f=d();this.size=0};h.prototype.has=function(f){return!!b(this,f).c};h.prototype.get=function(f){return(f=b(this,f).c)&&f.value};h.prototype.entries=function(){return c(this,function(f){return[f.key,f.value]})};h.prototype.keys=function(){return c(this,function(f){return f.key})};h.prototype.values=function(){return c(this,function(f){return f.value})};h.prototype.forEach=function(f,e){for(var g=this.entries(),k;!(k=g.next()).done;)k=k.value,
f.call(e,k[1],k[0],this)};h.prototype[Symbol.iterator]=h.prototype.entries;var m=0;return h});
x("Set",function(a){function d(c){this.a=new Map;if(c){c=q(c);for(var b;!(b=c.next()).done;)this.add(b.value)}this.size=this.a.size}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),b=new a(q([c]));if(!b.has(c)||1!=b.size||b.add(c)!=b||1!=b.size||b.add({x:4})!=b||2!=b.size)return!1;var h=b.entries(),l=h.next();if(l.done||l.value[0]!=c||l.value[1]!=c)return!1;l=h.next();return l.done||l.value[0]==c||4!=l.value[0].x||
l.value[1]!=l.value[0]?!1:h.next().done}catch(m){return!1}}())return a;d.prototype.add=function(c){c=0===c?0:c;this.a.set(c,c);this.size=this.a.size;return this};d.prototype.delete=function(c){c=this.a.delete(c);this.size=this.a.size;return c};d.prototype.clear=function(){this.a.clear();this.size=0};d.prototype.has=function(c){return this.a.has(c)};d.prototype.entries=function(){return this.a.entries()};d.prototype.values=function(){return this.a.values()};d.prototype.keys=d.prototype.values;d.prototype[Symbol.iterator]=
d.prototype.values;d.prototype.forEach=function(c,b){var h=this;this.a.forEach(function(l){return c.call(b,l,l,h)})};return d});x("Array.prototype.fill",function(a){return a?a:function(d,c,b){var h=this.length||0;0>c&&(c=Math.max(0,h+c));if(null==b||b>h)b=h;b=Number(b);0>b&&(b=Math.max(0,h+b));for(c=Number(c||0);c<b;c++)this[c]=d;return this}});var A=[8.498,9.989,12.191,16.445,27.607,29.835,31.85,37.944,45.49,45.643,46.935,50.96,53.365,60.114,67.621,69.55,69.645,77.232,83.559,92.915,95.673,96.651,99.211,99.361,101.355,101.432],B=new Set;function C(a,d){D++;var c=0===D%4?"#4285F4":1===D%4?"#DB4437":2===D%4?"#F4B400":"#0F9D58";this.g=a;this.u=d;this.o=c}var E=[];function F(a,d){this.x=a;this.y=d}function G(a,d){return Math.sqrt(Math.pow(a.x-d.x,2)+Math.pow(a.y-d.y,2))}function H(){this.a=this.b=0;this.h=[]}
function I(a,d){return a.h[Math.floor(d.y/a.a)][Math.floor((d.x-a.b)/a.a)]}function J(a,d){return 10>a&&0<=a&&0<=d&&10>d}
function K(){var a=L.getBoundingClientRect().height,d=L.getBoundingClientRect().width,c=new H;a/=10;var b=d/10;c.a=b>a?a:b;c.b=d/2-10*c.a/2;d=c.b;for(b=a=0;10>b;++b){for(var h=[],l=0;10>l;++l)h.push({i:d,j:a,o:"white",s:!1,l:"-"}),d+=c.a;c.h.push(h);d=c.b;a+=c.a}d=q(c.h);for(a=d.next();!a.done;a=d.next())for(a=q(a.value),b=a.next();!b.done;b=a.next()){h=101.432*Math.random();for(var m=l=0;26>m;++m)if(h<A[m]){l=m;break}b.value.l=String.fromCharCode(97+l)}return c}
function M(a,d){var c;B.add(a);var b=a;var h=b.length;var l=.25>Math.random()?!0:!1;l&&(b=b.split("").reverse().join(""));var m=Math.random();var f=.33>m?"vertical":.66>m?"diagonal":"horizontal";m=c=0;"vertical"===f?c=1:"diagonal"===f?m=c=1:"horizontal"===f&&(m=1);var e=Math.floor(10*Math.random()),g=Math.floor(10*Math.random());for(console.log("Now placing: ",b);;){var k=h;var p=e,t=g,w=f;if(!J(p,t))throw console.log("Index is: ",p,",",t),"Error - inital square location is not valid";--k;if("vertical"===
w)k=J(p,t+k);else if("horizontal"===w)k=J(p+k,t);else if("diagonal"===w)k=J(p+k,t+k);else throw"ERROR In doesWordFit, no valid option for direction";if(k)a:{k=e;p=g;for(t=0;t<b.length;++t){w=d.h[k][p];if(w.s&&w.l!=b.charAt(t)){k=!1;break a}k+=m;p+=c}k=!0}if(k)break;console.log("nooo");e=Math.floor(10*Math.random());g=Math.floor(10*Math.random())}b=e;h=g;l&&(a=a.split("").reverse().join(""));console.log("Part of word is at index: ",b,",",h);for(l=0;l<a.length;++l)g=d.h[b][h],b+=m,h+=c,g.l=a.charAt(l),
g.s=!0};var L=document.getElementById("wordSearchCanvas"),N=L.getContext("2d");function O(a){this.a=a;this.b=E}function P(a){N.clearRect(0,0,L.width,L.height);Q(a);if(0<a.b.length){a=q(a.b);for(var d=a.next();!d.done;d=a.next())d=d.value,N.fillStyle=d.o,N.strokeStyle=d.o,N.globalAlpha=.5,R(d.g,d.u),N.closePath(),N.fill(),N.globalAlpha=1,N.strokeStyle="black"}}
function Q(a){N.textAlign="center";N.font="30px Arial";for(var d=q(a.a.h),c=d.next();!c.done;c=d.next()){c=q(c.value);for(var b=c.next();!b.done;b=c.next())b=b.value,N.fillStyle=b.o,N.fillRect(b.i,b.j,a.a.a,a.a.a),N.fillStyle="black",N.fillText(b.l,b.i+a.a.a/2,b.j+a.a.a/2+10)}}
function R(a,d){var c=Math.atan2(d.y-a.y,d.x-a.x);d=new F(a.x+Math.sqrt(Math.pow(a.x-d.x,2)+Math.pow(a.y-d.y,2)),a.y);var b=a.x+(d.x-a.x)/2;N.save();N.lineWidth=5;N.translate(a.x,a.y);N.rotate(c);N.translate(-a.x,-a.y);N.beginPath();N.moveTo(b,a.y-15);N.arcTo(d.x+15,d.y-15,d.x+15,d.y,15);N.arcTo(d.x+15,d.y+15,b,a.y+15,15);N.arcTo(a.x-15,a.y+15,a.x-15,a.y,15);N.arcTo(a.x-15,a.y-15,b,a.y-15,15);N.lineTo(b,a.y-15);N.stroke();N.restore()};function S(a,d){this.a=a;this.m=d;this.b=!1}var D=-1;(function(){var a=K();M("mikita",a);M("patrick",a);M("laura",a);M("google",a);console.log(a);var d=new O(a),c=new S(a,d);window.addEventListener("mousedown",function(b){b=new F(b.clientX,b.clientY);var h=c.a,l=10*h.a;b.x<h.b+10*h.a&&b.y<l&&b.x>h.b&&0<b.y?(c.b=!0,b=I(c.a,b),c.g=new F(b.i+c.a.a/2,b.j+c.a.a/2),console.log("Hit!")):console.log("Miss!")});window.addEventListener("mousemove",function(b){b=new F(b.clientX,b.clientY);c.b&&(P(c.m),R(c.g,b))});window.addEventListener("mouseup",function(b){b=
new F(b.clientX,b.clientY);if(c.b){c.b=!1;b=I(c.a,b);b=new F(b.i+c.a.a/2,b.j+c.a.a/2);var h=c.g;if(b.x!==h.x||b.y!==h.y){var l=c.a,m=c.g,f=b;h=[];var e=l.a,g;if(m.x!==f.x&&m.y!==f.y){e=Math.sqrt(2*Math.pow(l.a,2));var k=g=e/Math.sqrt(2)}else.01>Math.abs(m.x-f.x)&&m.y!==f.y?(g=0,k=e):(g=e,k=0);m.y>f.y&&(k*=-1);m.x>f.x&&(g*=-1);m=I(l,m);m=new F(m.i+l.a/2,m.j+l.a/2);f=I(l,f);f=new F(f.i+l.a/2,f.j+l.a/2);e=G(m,f)/e+1;if(!(.001<Math.abs(e-Math.round(e))))for(m=new F(m.x,m.y),f=0;f<Math.round(e);++f)h.push(I(l,
m)),m=new F(m.x+g,m.y+k);l="";h=q(h);for(g=h.next();!g.done;g=h.next())l=l.concat(g.value.l);h=l;console.log("Word found is: ",h);B.has(h)?(E.push(new C(c.g,b)),c.m.b=E,P(c.m),R(c.g,b)):P(c.m);console.log("Distance from start to end is: ",G(c.g,b))}}});Q(d)})();
