/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function g(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}function p(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):{next:g(a)}};var t=[8.498,9.989,12.191,16.445,27.607,29.835,31.85,37.944,45.49,45.643,46.935,50.96,53.365,60.114,67.621,69.55,69.645,77.232,83.559,92.915,95.673,96.651,99.211,99.361,101.355,101.432],v=new Set;function w(a,c){x++;var d=0===x%4?"#4285F4":1===x%4?"#DB4437":2===x%4?"#F4B400":"#0F9D58";this.c=a;this.o=c;this.l=d}var y=[];function z(a,c){this.x=a;this.y=c}function A(a,c){return Math.sqrt(Math.pow(a.x-c.x,2)+Math.pow(a.y-c.y,2))}function B(){this.a=this.b=0;this.f=[]}
function C(a,c){return a.f[Math.floor(c.y/a.a)][Math.floor((c.x-a.b)/a.a)]}function D(a,c){return 10>a&&0<=a&&0<=c&&10>c}
function E(){var a=F.getBoundingClientRect().height,c=F.getBoundingClientRect().width,d=new B;a/=10;var b=c/10;d.a=b>a?a:b;d.b=c/2-10*d.a/2;c=d.b;for(b=a=0;10>b;++b){for(var h=[],f=0;10>f;++f)h.push({g:c,h:a,l:"white",m:!1,i:"-"}),c+=d.a;d.f.push(h);c=d.b;a+=d.a}c=p(d.f);for(a=c.next();!a.done;a=c.next())for(a=p(a.value),b=a.next();!b.done;b=a.next()){h=101.432*Math.random();for(var e=f=0;26>e;++e)if(h<t[e]){f=e;break}b.value.i=String.fromCharCode(97+f)}return d}
function G(a,c){var d;v.add(a);var b=a;var h=b.length;var f=.25>Math.random()?!0:!1;f&&(b=b.split("").reverse().join(""));var e=Math.random();var k=.33>e?"vertical":.66>e?"diagonal":"horizontal";e=d=0;"vertical"===k?d=1:"diagonal"===k?e=d=1:"horizontal"===k&&(e=1);var n=Math.floor(10*Math.random()),m=Math.floor(10*Math.random());for(console.log("Now placing: ",b);;){var l=h;var r=n,q=m,u=k;if(!D(r,q))throw console.log("Index is: ",r,",",q),"Error - inital square location is not valid";--l;if("vertical"===
u)l=D(r,q+l);else if("horizontal"===u)l=D(r+l,q);else if("diagonal"===u)l=D(r+l,q+l);else throw"ERROR In doesWordFit, no valid option for direction";if(l)a:{l=n;r=m;for(q=0;q<b.length;++q){u=c.f[l][r];if(u.m&&u.i!=b.charAt(q)){l=!1;break a}l+=e;r+=d}l=!0}if(l)break;console.log("nooo");n=Math.floor(10*Math.random());m=Math.floor(10*Math.random())}b=n;h=m;f&&(a=a.split("").reverse().join(""));console.log("Part of word is at index: ",b,",",h);for(f=0;f<a.length;++f)m=c.f[b][h],b+=e,h+=d,m.i=a.charAt(f),
m.m=!0};var F=document.getElementById("wordSearchCanvas"),H=F.getContext("2d");function I(a){this.a=a;this.b=y}function J(a){H.clearRect(0,0,F.width,F.height);K(a);if(0<a.b.length){a=p(a.b);for(var c=a.next();!c.done;c=a.next())c=c.value,H.fillStyle=c.l,H.strokeStyle=c.l,H.globalAlpha=.5,L(c.c,c.o),H.closePath(),H.fill(),H.globalAlpha=1,H.strokeStyle="black"}}
function K(a){H.textAlign="center";H.font="30px Arial";for(var c=p(a.a.f),d=c.next();!d.done;d=c.next()){d=p(d.value);for(var b=d.next();!b.done;b=d.next())b=b.value,H.fillStyle=b.l,H.fillRect(b.g,b.h,a.a.a,a.a.a),H.fillStyle="black",H.fillText(b.i,b.g+a.a.a/2,b.h+a.a.a/2+10)}}
function L(a,c){var d=Math.atan2(c.y-a.y,c.x-a.x);c=new z(a.x+Math.sqrt(Math.pow(a.x-c.x,2)+Math.pow(a.y-c.y,2)),a.y);var b=a.x+(c.x-a.x)/2;H.save();H.lineWidth=5;H.translate(a.x,a.y);H.rotate(d);H.translate(-a.x,-a.y);H.beginPath();H.moveTo(b,a.y-15);H.arcTo(c.x+15,c.y-15,c.x+15,c.y,15);H.arcTo(c.x+15,c.y+15,b,a.y+15,15);H.arcTo(a.x-15,a.y+15,a.x-15,a.y,15);H.arcTo(a.x-15,a.y-15,b,a.y-15,15);H.lineTo(b,a.y-15);H.stroke();H.restore()};function M(a,c){this.a=a;this.j=c;this.b=!1}var x=-1;(function(){var a=E();G("mikita",a);G("patrick",a);G("laura",a);G("google",a);console.log(a);var c=new I(a),d=new M(a,c);window.addEventListener("mousedown",function(b){b=new z(b.clientX,b.clientY);var h=d.a,f=10*h.a;b.x<h.b+10*h.a&&b.y<f&&b.x>h.b&&0<b.y?(d.b=!0,b=C(d.a,b),d.c=new z(b.g+d.a.a/2,b.h+d.a.a/2),console.log("Hit!")):console.log("Miss!")});window.addEventListener("mousemove",function(b){b=new z(b.clientX,b.clientY);d.b&&(J(d.j),L(d.c,b))});window.addEventListener("mouseup",function(b){b=
new z(b.clientX,b.clientY);if(d.b){d.b=!1;b=C(d.a,b);b=new z(b.g+d.a.a/2,b.h+d.a.a/2);var h=d.c;if(b.x!==h.x||b.y!==h.y){var f=d.a,e=d.c,k=b;h=[];var n=f.a,m;if(e.x!==k.x&&e.y!==k.y){n=Math.sqrt(2*Math.pow(f.a,2));var l=m=n/Math.sqrt(2)}else.01>Math.abs(e.x-k.x)&&e.y!==k.y?(m=0,l=n):(m=n,l=0);e.y>k.y&&(l*=-1);e.x>k.x&&(m*=-1);e=C(f,e);e=new z(e.g+f.a/2,e.h+f.a/2);k=C(f,k);k=new z(k.g+f.a/2,k.h+f.a/2);n=A(e,k)/n+1;if(!(.001<Math.abs(n-Math.round(n))))for(e=new z(e.x,e.y),k=0;k<Math.round(n);++k)h.push(C(f,
e)),e=new z(e.x+m,e.y+l);f="";h=p(h);for(m=h.next();!m.done;m=h.next())f=f.concat(m.value.i);h=f;console.log("Word found is: ",h);v.has(h)?(y.push(new w(d.c,b)),d.j.b=y,J(d.j),L(d.c,b)):J(d.j);console.log("Distance from start to end is: ",A(d.c,b))}}});K(c)})();
